import type { IconType } from "react-icons";
import {
  SiAndroid,
  SiArduino,
  SiC,
  SiCplusplus,
  SiCss,
  SiDart,
  SiDigitalocean,
  SiDocker,
  SiEspressif,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGithubactions,
  SiGooglecloud,
  SiGooglecolab,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJetpackcompose,
  SiJupyter,
  SiKotlin,
  SiMongodb,
  SiMysql,
  SiN8N,
  SiNextdotjs,
  SiNodedotjs,
  SiOllama,
  SiOpencv,
  SiPrisma,
  SiOpenjdk,
  SiPm2,
  SiPostman,
  SiPostgresql,
  SiPycharm,
  SiPython,
  SiPytorch,
  SiRaspberrypi,
  SiReact,
  SiRedis,
  SiLinux,
  SiMediapipe,
  SiScikitlearn,
  SiSupabase,
  SiTensorflow,
  SiTypescript,
  SiVercel,
} from "react-icons/si";
import {
  HiBeaker,
  HiCpuChip,
  HiLanguage,
  HiMagnifyingGlass,
  HiPencilSquare,
  HiRocketLaunch,
} from "react-icons/hi2";

const ICONS: Record<string, IconType> = {
  SiPython,
  SiC,
  SiCplusplus,
  SiOpenjdk,
  SiKotlin,
  SiHtml5,
  SiCss,
  SiDart,
  SiJavascript,
  SiTypescript,
  SiNodedotjs,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiOpencv,
  SiJetpackcompose,
  SiAndroid,
  SiFlutter,
  SiDocker,
  SiJenkins,
  SiGithubactions,
  SiDigitalocean,
  SiVercel,
  SiPm2,
  SiGooglecloud,
  SiFlask,
  SiFastapi,
  SiSupabase,
  SiPostman,
  SiFirebase,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiGit,
  SiPycharm,
  SiJupyter,
  SiGooglecolab,
  SiN8N,
  SiNextdotjs,
  SiOllama,
  SiExpress,
  SiReact,
  SiPrisma,
  SiRedis,
  SiLinux,
  SiMediapipe,
  SiRaspberrypi,
  SiArduino,
  SiEspressif,
  HiChip: HiCpuChip,
  HiTranslate: HiLanguage,
  HiSearch: HiMagnifyingGlass,
  HiDraft: HiPencilSquare,
  HiBeaker,
  HiRocket: HiRocketLaunch,
};

const BY_NAME: Record<string, string> = {
  python: "SiPython",
  c: "SiC",
  "c++": "SiCplusplus",
  java: "SiOpenjdk",
  kotlin: "SiKotlin",
  html: "SiHtml5",
  css: "SiCss",
  dart: "SiDart",
  "next.js": "SiNextdotjs",
  ollama: "SiOllama",
  "local llms": "SiOllama",
  express: "SiExpress",
  "react native": "SiReact",
  prisma: "SiPrisma",
  redis: "SiRedis",
  linux: "SiLinux",
  mediapipe: "SiMediapipe",
  javascript: "SiJavascript",
  typescript: "SiTypescript",
  "node.js": "SiNodedotjs",
  nodejs: "SiNodedotjs",
  tensorflow: "SiTensorflow",
  pytorch: "SiPytorch",
  "scikit-learn": "SiScikitlearn",
  opencv: "SiOpencv",
  "jetpack compose": "SiJetpackcompose",
  "android sdk": "SiAndroid",
  "android studio": "SiAndroid",
  flutter: "SiFlutter",
  docker: "SiDocker",
  jenkins: "SiJenkins",
  "github actions": "SiGithubactions",
  digitalocean: "SiDigitalocean",
  vercel: "SiVercel",
  pm2: "SiPm2",
  "google cloud platform": "SiGooglecloud",
  "google cloud platform (gcp)": "SiGooglecloud",
  flask: "SiFlask",
  fastapi: "SiFastapi",
  supabase: "SiSupabase",
  "rest apis": "SiPostman",
  postman: "SiPostman",
  firebase: "SiFirebase",
  postgresql: "SiPostgresql",
  mysql: "SiMysql",
  mongodb: "SiMongodb",
  git: "SiGit",
  pycharm: "SiPycharm",
  jupyter: "SiJupyter",
  colab: "SiGooglecolab",
  n8n: "SiN8N",
  dockerhub: "SiDocker",
  "raspberry pi 5": "SiRaspberrypi",
  "arduino uno": "SiArduino",
  esp32: "SiEspressif",
  "esp32-cam": "SiEspressif",
};

export function iconKeyFor(name: string): string | null {
  const key = name.trim().toLowerCase();
  const base = key.split("(")[0].trim();
  return BY_NAME[key] || BY_NAME[base] || null;
}

export function SkillIcon({ name }: { name?: string | null }) {
  const Icon = ICONS[name || ""] || HiCpuChip;
  return <Icon aria-hidden className="skill-icon" />;
}
